### ISSUE TITLE
Ex. 3.1.1: Getting "KeyError: 'continue'" when iterating over category pages (SAMPLE ISSUE)

### ISSUE THREAD

**Issue by ulfaslak** [ulfaslak/computational_analysis_of_big_data_2018_spring#1]
I've written a function that loads all members of a category into a list and returns it. If I insert print statements in the loop it seems to run for a while, but then eventually gives me an error `KeyError: 'continue'`. See code below:

```Python
import requests as rq

def get_list_of_heroes(cla):
    """Input 'heroes' or 'villains' and return list of characters."""
    # Format query
    endpoint = "https://en.wikipedia.org/w/api.php?"
    action = "action=query"
    _list = "list=categorymembers"
    _format = "format=json"
    cmtitle = "cmtitle=Category:Marvel_Comics_super%s" % cla
    cmlimit = "cmlimit=500"
    cmcontinue = ""

    characters = []
    while True:
        query_url = "&".join([endpoint, action, _list, cmtitle, _format, cmlimit, cmcontinue])
        data = rq.get(query_url).json()
        characters.extend([(c['title'], c['pageid']) for c in data['query']['categorymembers']])
        cmcontinue = 'cmcontinue=' + data['continue']['cmcontinue']

    return characters

# Extract lists of characters
superheroes = get_list_of_heroes('heroes')
```

Anyone see what's wrong here? I've stared myself blind in this.

**Comment by returnop** [comment]
Hi,

The exception is being raised because the data dictionary does not have a 'continue' key when you are on the last "page" of categories. If you print the data, you will see it prints fine until you get to around the superheroes who have names that start with characters at the end of the alphabet.

So, if you add a line of code to check if it is the last page, (by checking if the 'continue' key actually exists), this should fix the issue. Note that you will want to put it after you extend the characters list, so that the last page is still included in the returned results. 

See code below.

```python
...
    while True:
        query_url = "&".join([endpoint, action, _list, cmtitle, _format, cmlimit, cmcontinue])
        data = rq.get(query_url).json()
        characters.extend([(c['title'], c['pageid']) for c in data['query']['categorymembers']])
        
        if not "continue" in data:
            return characters

        cmcontinue = 'cmcontinue=' + data['continue']['cmcontinue']

    return characters
...
```

Please update this ticket if this resolves your issue or otherwise.

**Comment by ulfaslak** [comment]
Solved it!
