### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by valeriehuang19** [ulfaslak/computational_analysis_of_big_data_2018_spring#4]
When using the code `re.findall(r"\d{4}\)", re.findall(r"debut.+?\n", markup_text)[0])[0][:-1]`

I have an error.

My test code is like this
```
import re

name = "Silvermane"
url = "https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&format=json&titles=%s" % name
data = rq.get(url).json()
re.findall(r"\d{4}\)", re.findall(r"debut.+?\n", url)[0])[0][:-1]
```

and the error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-86-bdbc174fd08d> in <module>()
      4 url = "https://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&format=json&titles=%s" % name
      5 data = rq.get(url).json()
----> 6 re.findall(r"\d{4}\)", re.findall(r"debut.+?\n", url)[0])[0][:-1]

IndexError: list index out of range`

**Comment by ulfaslak** [comment]
The error basically says: "Hey, you are trying to get an element by its index from this list, but there is no element for that index in this list". You see it's happening on line 6 in your regex so that's what we need to debug. `re.findall` returns a list, so what I think is happening is that one of your regex searches is finding nothing (i.e returning an empty list), and when you then try to get the zero'th element from that list, you get that error. Try printing both the inner and outer regex matches on line 6 and see which one returns the empty list.

**Comment by ertroyer** [comment]
Once we have identified which one is returning the empty list, how do we go about correcting this exception and continue onto other files? I've noticed, when we manually read the text file, that the debut year is not immediately following the word "debut" so I'm wondering if that is affecting it (see the photo below for what I mean).
<img width="640" alt="screen shot 2018-02-26 at 8 45 46 pm" src="https://user-images.githubusercontent.com/32071201/36691585-1127a1c2-1b36-11e8-8547-4d8357c3c151.png">

**Comment by valeriehuang19** [comment]
@ertroyer 
I think I figured out the problem!
`r"\d{4}\)"`  this part is how you find the year in the string
I used something like `year = re.findall(r"\d{4}\)", re.findall(r"debut.+?\n", data)[0])[-1].split(')')[0]
`
