### ISSUE TITLE
Do columns in ambiguous and the full data team alliances need to be the same and ordered the same way?

### ISSUE THREAD

**Issue by tnelsen16** [ulfaslak/computational_analysis_of_big_data_2018_spring#7]
Currently trying to predict the probability on the ambiguous characters, but the team alliance matrices have a different number of alliances. We are working on getting rid of the columns that are not in both, but once we do that do we need to sort the columns in ambiguous so that they mirror each other? If so, we are having a hard time figuring out how to do this.

**Comment by ulfaslak** [comment]
The columns NEED to represent the same teams, otherwise the decision boundary that your model learns, will look like an arbitrary line in the ambiguous dataset which most likely does not separate the classes very well. However, if you look inside the data folder, I uploaded the team alliances matrix for the ambiguous characters. It has the same formatting as the one for heroes and villains, only it doesn't contain the class.

**Comment by tnelsen16** [comment]
The alliance columns in the ambiguous matrix that you gave us is not sorted alphabetically, but the heroes/villains one is. Is that still considered the same formatting and then doesn't matter?

**Comment by tnelsen16** [comment]
Just kidding I was looking at the not-updated version
