### ISSUE TITLE
Ex. 6.2.1

### ISSUE THREAD

**Issue by valeriehuang19** [ulfaslak/computational_analysis_of_big_data_2018_spring#9]
I used about the same code as before get_alliance but it shows an error
![image](https://user-images.githubusercontent.com/21328329/37426970-3295c7be-27c8-11e8-99c4-047a0c2ec1e4.png)

![image](https://user-images.githubusercontent.com/21328329/37426987-3eb8ec74-27c8-11e8-9e8a-5fdfc44d1a82.png)

**Comment by ulfaslak** [comment]
Hey, sorry for the super late answer, this somehow slipped under my radar.

I'm afraid I don't have enough information here to give you a solution. I would suggest you check that your folder and files are located in the path you're referencing in your code, but otherwise I don't know. Ask me during class today if this still is a problem.
